name: proper use of variables (secrets)

on: push

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    name: staging
    env:
      AWS_REGION: us-east-1
      CONTAINER_NAME: nice-app-service
    steps:
      -  name: Checkout the code
         uses: actions/checkout@v4
      -  name: configure aws creds
         uses: aws-actions/congure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
